// Inlines the images in src/assets into src/assets/generated.ts as data URLs. Bun's dataurl and
// base64 loaders returned an empty string for these files, so the build does it explicitly.
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';

const dir = 'src/assets';
const lines = readdirSync(dir)
  .filter((f) => f.endsWith('.png'))
  .map((f) => {
    const name = f.replace(/\.png$/, '').replace(/-(\w)/g, (_, c: string) => c.toUpperCase());
    return `export const ${name} = 'data:image/png;base64,${readFileSync(`${dir}/${f}`).toString('base64')}';`;
  });
writeFileSync(`${dir}/generated.ts`, `// Generated by scripts/assets.ts; do not edit.\n${lines.join('\n')}\n`);
console.log(`inlined ${lines.length} image(s)`);
