import type { Language } from './survey';

// Every label the survey screens show, in both languages. One clause per string. Kiswahili wording
// needs review by a native speaker.
export const STRINGS = {
  en: {
    languageTitle: 'Choose your language',
    languageLead: 'Select your preferred language for the Wren app',
    continue: 'Continue',
    signInTitle: 'Sign in to Wren',
    signInLead: 'Create and manage your business booking site',
    google: 'Continue with Google',
    signInFailed: 'Google sign-in did not finish',
    businessTitle: 'Tell us about your business',
    businessLead: 'Contact details and business photos',
    name: 'Business name',
    phone: 'Phone number',
    phoneHint: 'Your phone number needs its country code',
    location: 'Location',
    about: 'About your business',
    optional: 'Optional',
    photos: 'Photos of your business',
    addPhoto: 'Add photo',
    photosLater: 'Photo upload comes in a later build',
    servicesTitle: 'Tell us about your business',
    servicesLead: 'Add the services clients can book with you',
    serviceType: 'Service type',
    selectOption: 'Select option',
    addCustom: 'Add custom',
    customName: 'Service name',
    serviceAbout: 'About this service',
    duration: 'Duration',
    hr: 'hr',
    min: 'min',
    price: 'Price per client',
    capacity: 'Max capacity',
    clients: 'clients',
    addService: 'Add another service',
    removeService: 'Remove',
    availabilityTitle: 'When are you available?',
    availabilityLead: 'Set the days and hours clients can book your services',
    days: 'Available days',
    daysHint: 'Tap to toggle availability',
    slots: 'Time slots',
    regularHours: 'Regular hours',
    addSlot: 'Add time slot',
    slotHint: 'Times use the 24-hour clock',
    reviewTitle: 'Review and create site',
    reviewLead: 'Your online booking site is ready to be created',
    servicesDone: 'Services configured',
    scheduleDone: 'Booking schedule set',
    contactDone: 'Contact details verified',
    create: 'Create business site',
    creating: 'Creating your site',
    created: 'Your site preview',
    createFailed: 'The site could not be created',
    tryAgain: 'Try again',
    next: 'Next',
  },
  sw: {
    languageTitle: 'Chagua lugha yako',
    languageLead: 'Chagua lugha ya kutumia programu ya Wren',
    continue: 'Endelea',
    signInTitle: 'Ingia kwenye Wren',
    signInLead: 'Tengeneza na usimamie tovuti ya biashara yako',
    google: 'Endelea na Google',
    signInFailed: 'Kuingia na Google hakukukamilika',
    businessTitle: 'Tuambie kuhusu biashara yako',
    businessLead: 'Mawasiliano na picha za biashara',
    name: 'Jina la biashara',
    phone: 'Namba ya simu',
    phoneHint: 'Namba ya simu inahitaji msimbo wa nchi',
    location: 'Mahali',
    about: 'Kuhusu biashara yako',
    optional: 'Si lazima',
    photos: 'Picha za biashara yako',
    addPhoto: 'Ongeza picha',
    photosLater: 'Kupakia picha kutakuja baadaye',
    servicesTitle: 'Tuambie kuhusu biashara yako',
    servicesLead: 'Ongeza huduma ambazo wateja wanaweza kuweka nafasi',
    serviceType: 'Aina ya huduma',
    selectOption: 'Chagua',
    addCustom: 'Ongeza nyingine',
    customName: 'Jina la huduma',
    serviceAbout: 'Kuhusu huduma hii',
    duration: 'Muda',
    hr: 'saa',
    min: 'dakika',
    price: 'Bei kwa mteja',
    capacity: 'Idadi ya juu',
    clients: 'wateja',
    addService: 'Ongeza huduma nyingine',
    removeService: 'Ondoa',
    availabilityTitle: 'Unapatikana lini?',
    availabilityLead: 'Weka siku na saa ambazo wateja wanaweza kuweka nafasi',
    days: 'Siku zinazopatikana',
    daysHint: 'Gusa kuwasha au kuzima siku',
    slots: 'Nafasi za muda',
    regularHours: 'Saa za kawaida',
    addSlot: 'Ongeza nafasi ya muda',
    slotHint: 'Saa zinatumia mfumo wa saa 24',
    reviewTitle: 'Kagua na utengeneze tovuti',
    reviewLead: 'Tovuti yako ya kuweka nafasi iko tayari kutengenezwa',
    servicesDone: 'Huduma zimewekwa',
    scheduleDone: 'Ratiba imewekwa',
    contactDone: 'Mawasiliano yamethibitishwa',
    create: 'Tengeneza tovuti ya biashara',
    creating: 'Inatengeneza tovuti yako',
    created: 'Hakikisho la tovuti yako',
    createFailed: 'Tovuti haikuweza kutengenezwa',
    tryAgain: 'Jaribu tena',
    next: 'Endelea',
  },
} as const satisfies Record<Language, Record<string, string>>;

export type Strings = (typeof STRINGS)[Language];

// The language list on the first screen, each named only in its own language.
export const LANGUAGE_CHOICES: { id: Language; label: string; code: string }[] = [
  { id: 'en', label: 'English', code: 'EN' },
  { id: 'sw', label: 'Kiswahili', code: 'SW' },
];

export const DAY_LETTERS: Record<Language, string[]> = {
  en: ['M', 'T', 'W', 'T', 'F', 'S', 'S'],
  sw: ['Jt', 'Jn', 'Jtn', 'Al', 'Ij', 'Jm', 'Jp'],
};
